// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<cs_beatheart> (cs_beatheart.Tag);
		Protocol.SetRequest<SprotoType.cs_beatheart.request> (cs_beatheart.Tag);
		Protocol.SetResponse<SprotoType.cs_beatheart.response> (cs_beatheart.Tag);

		Protocol.SetProtocol<cs_create> (cs_create.Tag);
		Protocol.SetRequest<SprotoType.cs_create.request> (cs_create.Tag);
		Protocol.SetResponse<SprotoType.cs_create.response> (cs_create.Tag);

		Protocol.SetProtocol<cs_delete> (cs_delete.Tag);
		Protocol.SetRequest<SprotoType.cs_delete.request> (cs_delete.Tag);
		Protocol.SetResponse<SprotoType.cs_delete.response> (cs_delete.Tag);

		Protocol.SetProtocol<cs_login> (cs_login.Tag);
		Protocol.SetRequest<SprotoType.cs_login.request> (cs_login.Tag);
		Protocol.SetResponse<SprotoType.cs_login.response> (cs_login.Tag);

		Protocol.SetProtocol<cs_logout> (cs_logout.Tag);
		Protocol.SetRequest<SprotoType.cs_logout.request> (cs_logout.Tag);
		Protocol.SetResponse<SprotoType.cs_logout.response> (cs_logout.Tag);

		Protocol.SetProtocol<cs_map_choose> (cs_map_choose.Tag);
		Protocol.SetRequest<SprotoType.cs_map_choose.request> (cs_map_choose.Tag);

		Protocol.SetProtocol<sc_map_enter> (sc_map_enter.Tag);
		Protocol.SetRequest<SprotoType.sc_map_enter.request> (sc_map_enter.Tag);

	}

	public class cs_beatheart {
		public const int Tag = 3;
	}

	public class cs_create {
		public const int Tag = 11;
	}

	public class cs_delete {
		public const int Tag = 12;
	}

	public class cs_login {
		public const int Tag = 1;
	}

	public class cs_logout {
		public const int Tag = 2;
	}

	public class cs_map_choose {
		public const int Tag = 31;
	}

	public class sc_map_enter {
		public const int Tag = 32;
	}

}